version: "3.7"
services:
  hadoop:
    build: ./images/hadoop
    container_name: hadoop
    hostname: hadoop
    ports:
      - "9870:9870" # HDFS / WebHDFS
      - "8088:8088" # ResourceManager
      - "9000:9000" # Conexao Externa HDFS
      - "8042:8042" # DataNode
      - "9864:9864" # DataNode WebUI
      - "8888:8888" #Jupyter

    volumes:
      - hadoop_namenode:/usr/hadoop/data/namenode
      - hadoop_datanode:/usr/hadoop/data/datanode
      - ./notebooks:/usr/notebooks
      - jupyterlab_config:/home/jovyan/.local/share/jupyter
      - jupyterlab_config:/home/jovyan/.jupyter
    networks:
      - danilake

networks:
  danilake:
    driver: bridge

volumes:
  jupyterlab_config:
  hadoop_namenode:
  hadoop_datanode: