version: "3.7"
services:
  hadoop1:
    build: ./images/hadoop
    container_name: hadoop
    hostname: hadoop
    ports:
      - "9870:9870" # HDFS / WebHDFS
      - "8088:8088" # ResourceManager
      - "9000:9000" # Conexao Externa HDFS
      - "8042:8042" # DataNode
      - "9864:9864" # DataNode WebUI

    volumes:
      - hadoop_namenode1:/usr/hadoop/data/namenode
      - hadoop_datanode1:/usr/hadoop/data/datanode
    networks:
      - danilake1

  jupyter:
    build: ./images/jupyter
    container_name: jupyter
    hostname: jupyter
    ports:
      - "8888:8888" #Jupyter

    volumes:
      - ./notebooks:/usr/notebooks
      - jupyterlab_config:/home/jovyan/.local/share/jupyter
      - jupyterlab_config:/home/jovyan/.jupyter
    networks:
      - danilake1

networks:
  danilake1:
    driver: bridge

volumes:
  jupyterlab_config:
  hadoop_namenode1:
  hadoop_datanode1: