version: "3.7"
services:
  jupyter:
    build: ./images/jupyter
    container_name: jupyter
    hostname: jupyter
    ports:
      - "8888:8888" 
      - "9000:9000" 
    volumes:
      - ./notebooks:/notebooks
      - jupyterlab_config:/home/jovyan/.local/share/jupyter
      - jupyterlab_config:/home/jovyan/.jupyter
  hadoop:
    build: ./images/hadoop
    container_name: hadoop
    hostname: hadoop
    ports:
      - "9870:9870"

volumes:
  jupyterlab_config:
