name: myenv
channels:
  - conda-forge
dependencies:
  - python==3.11.4
  - matplotlib
  - numpy
  - pandas
  - scikit-learn==1.3.0
  - seaborn
  - plotly
  - ipython
  - ipykernel
  - cython
  - jupyterlab
  - scipy
  - ipympl
  - lightgbm==4.5.0
  - xgboost==2.1.1
  - shap
  - imbalanced-learn==0.12.4
